version: '2'

services:

  esn:
    container_name: esn
    image: linagora/esn:1.9.0-rc6
    # ports:
    #  - "8080:8080"
    networks:
      - default
      - web
    expose:
      - 8080
    volumes:
      - ./docker/config:/var/www/docker/config:ro
    environment:
      - DOCKER_IP=localhost
      - PROVISION=${PROVISION}
      - CONFIG_DIR=/var/www/docker/config
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_PROTOCOL=amqp
      - AMQP_USERNAME=guest
      - AMQP_PASSWORD=guest
      - WEB_HOST=${DOCKER_IP}
      - WEB_PORT=8080
      - DAV_SERVER_HOST=sabre
      - DAV_SERVER_PORT=80
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}
      - JMAP_SERVER_HOST=james
      - JMAP_SERVER_PORT=80
      - MAIL_BROWSER=false
      - SMTP_HOST=james
      - SMTP_PORT=25
      - JAMES_WEBADMIN_HOST=james
      - JAMES_WEBADMIN_PORT=8000
    links:
      - redis
      - mongo
      - rabbitmq
      - sabre
      - elasticsearch
    labels:
      traefik.enable: "true"
      traefik.http.routers.openbaas.entryPoints: web
      traefik.http.routers.openbaas.tls.certResolver: default
      traefik.http.routers.openbaas.rule: Host(`openbaas.internetapi.cn`, `ob.internetapi.cn`)
      traefik.http.routers.openbaas.middlewares: redirectOb@docker
      traefik.http.middlewares.redirectOb.redirectRegex.regex: ob.internetapi.cn(.*)
      traefik.http.middlewares.redirectOb.redirectRegex.replacement: openbaas.internetapi.cn$${1}

  redis:
    container_name: esn_redis
    image: redis:6.2.1-alpine3.13 
    volumes:
      - redis-data:/data
    # ports:
    #   - "6379:6379"
    expose:
      - 6379

  rabbitmq:
    container_name: esn_rabbitmq
    image: rabbitmq:3.8.14-management
    hostname: esn-rabbit
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    expose:
      - 5672
      - 15672

  mongo:
    container_name: esn_mongo
    image: mongo:4.4.4
    command: ["mongod", "--smallfiles"]
    volumes:
      - mongo-data:/data/db
    # ports:
    #   - "27017:27017"
    expose:
      - 27017

  elasticsearch:
    container_name: esn_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    # ports:
    #   - "9200:9200"
    expose:
      - 9200
    environment:
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}
      - discovery.type=single-node

  sabre:
    container_name: esn_sabre
    image: linagora/esn-sabre:1.9.0-rc6
    ports:
      - "8001:80"
    environment:
      - SABRE_MONGO_HOST=mongo
      - SABRE_MONGO_PORT=27017
      - ESN_MONGO_HOST=mongo
      - ESN_MONGO_PORT=27017
      - ESN_MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - ESN_HOST=esn
      - ESN_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
    links:
      - mongo
    volumes:
      - ${ESN_PATH}/docker/config/jwt/public:/var/www/config/esn.key.pub

  james:
    container_name: esn_james
    depends_on:
      - esn # to have configuration ready in shared volume
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
    entrypoint: bash -c "java -Dlogback.configurationFile=/root/conf/logback.xml -Dworking.directory=/root/ -jar james-server.jar"
    image: linagora/james-rabbitmq-project:openpaas-1.10.0-rc1
    hostname: open-paas.org
    ports:
      # - "1080:80"   # JMAP
      # - "1025:25"   # SMTP without authentication
      # - "1110:110"  # POP3
      # - "1143:143"  # IMAP
      - "465:465"  # SMTP with authentication and socketTLS enabled
      - "587:587"  # SMTP with authentication and startTLS enabled
      - "993:993"  # IMAP with socketTLS enabled
      # - "8000:8000" # Web Admin interface (unsecured: expose at your own risks)
    expose:
      - 80
      - 25
      - 110
      - 143
      - 465
      - 587
      - 993
      - 8000
    volumes:
      - ./docker/config/james:/root/conf
      - ./docker/config/jwt/public:/root/conf/jwt_publickey

  cassandra:
    image: cassandra:4.0
    volumes:
      - cassandra-data:/var/lib/cassandra
    # ports:
    #   - "9042:9042"
    expose:
      - 9042

  tika:
    image: apache/tika:1.25
    expose:
      - 9998

volumes:
  redis-data:
    driver_opts:
      type: none
      device: ${PWD}/../data/redis/data
      o: bind
  rabbitmq-data:
    driver_opts:
      type: none
      device: ${PWD}/../data/rabbitmq/data
      o: bind
  mongo-data:
    driver_opts:
      type: none
      device: ${PWD}/../data/mongo/data
      o: bind
  elasticsearch-data:
    driver_opts:
      type: none
      device: ${PWD}/../data/elasticsearch/data
      o: bind
  cassandra-data:
    driver_opts:
      type: none
      device: ${PWD}/../data/cassandra/data
      o: bind

networks:
  web:
    external: true
